/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

// [MODIFY] Tiling 常量和结构体 - kernel 和 host 共用
// 此文件只含纯 C/C++ 语法，不含 __aicore__、__gm__ 等 ASC 关键字

#pragma once

#include <cstdint>

// [CONFIG] 单次搬运/处理的数据量（元素数），影响 UB 内存占用
// 常用值: float32 用 4096/8192，float16 用 8192/16384
constexpr uint32_t TILE_LENGTH = 4096;
constexpr uint32_t DOUBLE_BUFFER = 2;

// [MODIFY] Tiling 数据结构 - 向核函数传递的运行时参数
struct AddTilingData {
    uint32_t blockNum;
    uint64_t totalLength;
    uint64_t numPerCore;
    uint64_t tailNumLastCore;
};
