#!/usr/bin/env python3
# coding: utf-8
# Copyright (c) 2024-2026 Huawei Technologies Co., Ltd.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# -----------------------------------------------------------------------------
# snapshot_generator.py
#
# Reads a validated snapshot manifest and produces three artifacts under
# custom/<op>/_debug/:
#
#   1. <op>_<module>_snapshot.py       — copy of the module kernel with
#                                        inspection_<name> buffers assembled
#                                        at each intermediate's probe point.
#   2. <op>_golden_modular_snapshot.py — copy of the modular golden with
#                                        module_<k>_inspect() extended to
#                                        return per-iteration intermediates.
#   3. run_snapshot_bisect.sh          — one-command runner that invokes
#                                        snapshot_bisect.py for all three modes
#                                        (torch/sim/npu) and prints drift-onset
#                                        per intermediate.
#
# Design principle: the generator does NOT do full AST rewriting. Instead it
# relies on MARKER COMMENTS the kernel author leaves in the module file.
# Markers are:
#
#   # <<< SNAPSHOT:before_nt_loop
#   # >>> SNAPSHOT:before_nt_loop
#   # <<< SNAPSHOT:inside_nt_loop
#   # >>> SNAPSHOT:inside_nt_loop
#   # <<< SNAPSHOT:after_nt_loop
#   # >>> SNAPSHOT:after_nt_loop
#
# For each intermediate in the manifest, the generator inserts a small
# pypto.assemble block just before the corresponding closing marker. This
# keeps the generator simple, deterministic, and diff-friendly.
#
# The golden side uses the same marker convention in the modular golden.
# -----------------------------------------------------------------------------

from __future__ import annotations

import argparse
import logging
import os
import re
import stat
import sys
from pathlib import Path
from typing import Dict, List, NamedTuple, Optional

# Local import — the manifest loader lives next to us.
sys.path.insert(0, str(Path(__file__).resolve().parent))
from snapshot_manifest_schema import load_manifest   # noqa: E402


MARKER_OPEN = re.compile(
    r"^(\s*)# <<< SNAPSHOT:("
    r"before_nt_loop|inside_nt_loop|after_nt_loop|"
    r"SIG_IMPL|SIG_JIT|CALL_IMPL|"
    r"HOST_WRAPPER_INSPECT_ALLOC|HOST_WRAPPER_INSPECT_PASS"
    r")\s*$"
)
MARKER_CLOSE = re.compile(
    r"^(\s*)# >>> SNAPSHOT:("
    r"before_nt_loop|inside_nt_loop|after_nt_loop|"
    r"SIG_IMPL|SIG_JIT|CALL_IMPL|"
    r"HOST_WRAPPER_INSPECT_ALLOC|HOST_WRAPPER_INSPECT_PASS"
    r")\s*$"
)

# Vocabulary of probe-point markers that take intermediate-probe blocks.
PROBE_REGIONS = {"before_nt_loop", "inside_nt_loop", "after_nt_loop"}


# -----------------------------------------------------------------------------
# Impl-side code generation
# -----------------------------------------------------------------------------

def _gen_impl_probe_block(intermediate: Dict, indent: str) -> List[str]:
    """
    Generate the pypto.assemble probe lines for one intermediate at its probe
    point. The generated code writes into inspection_<name>.

    Buffer shape is [B, H, NT, *intermediate.shape] for inside_nt_loop probes,
    [B, H, *intermediate.shape] for before/after probes (no iteration axis).
    """
    name = intermediate["name"]
    shape = intermediate["shape"]
    pp = intermediate["probe_point"]
    ind = indent

    if pp == "inside_nt_loop":
        # Expected local variables in scope at the probe point: b, h, c (= NT-1-i for reverse scan, i for forward).
        # We wrap the rank-N intermediate to rank-(N+3) by prepending [1,1,1,...].
        wrap = "[1, 1, 1, " + ", ".join(str(s) for s in shape) + "]"
        offset = "[b, h, c, " + ", ".join("0" for _ in shape) + "]"
        return [
            f"{ind}# AUTO-GENERATED by snapshot_generator.py — probe for {name}",
            f"{ind}_probe_{name}_wrapped = pypto.reshape({name}, {wrap})",
            f"{ind}pypto.assemble(_probe_{name}_wrapped, {offset}, inspection_{name})",
        ]
    if pp in ("before_nt_loop", "after_nt_loop"):
        # Expected locals in scope: b, h (no iteration axis).
        wrap = "[1, 1, " + ", ".join(str(s) for s in shape) + "]"
        offset = "[b, h, " + ", ".join("0" for _ in shape) + "]"
        return [
            f"{ind}# AUTO-GENERATED by snapshot_generator.py — probe for {name}",
            f"{ind}_probe_{name}_wrapped = pypto.reshape({name}, {wrap})",
            f"{ind}pypto.assemble(_probe_{name}_wrapped, {offset}, inspection_{name})",
        ]
    raise ValueError(f"unknown probe_point {pp!r}")


def _gen_sig_impl_kwargs(intermediates: List[Dict], indent: str) -> List[str]:
    """kwargs for the _<op>_kernel_impl signature — plain Python, defaulting to None."""
    return [f"{indent}inspection_{e['name']}=None," for e in intermediates]


def _gen_sig_jit_kwargs(intermediates: List[Dict], indent: str) -> List[str]:
    """kwargs for the JIT entry — annotated with pypto.Tensor, default None."""
    return [
        f"{indent}inspection_{e['name']}: pypto.Tensor([], pypto.DT_FP32) = None,"
        for e in intermediates
    ]


def _gen_call_impl_kwargs(intermediates: List[Dict], indent: str) -> List[str]:
    """Keyword-argument pass-through from the JIT entry into _<op>_kernel_impl."""
    return [f"{indent}inspection_{e['name']}=inspection_{e['name']}," for e in intermediates]


def _gen_host_wrapper_alloc(intermediates: List[Dict], indent: str) -> List[str]:
    """
    Allocate zero buffers inside host_wrapper(). Shape depends on probe_point
    (same rule as _alloc_inspection_buffers in snapshot_bisect.py).
    """
    out: List[str] = []
    for entry in intermediates:
        name = entry["name"]
        shape = entry["shape"]
        if entry["probe_point"] == "inside_nt_loop":
            shape_expr = "[B, H, NT, " + ", ".join(str(s) for s in shape) + "]"
        else:
            shape_expr = "[B, H, " + ", ".join(str(s) for s in shape) + "]"
        out.append(
            f"{indent}inspection_{name} = torch.zeros({shape_expr}, dtype=torch.float32, device=x.device) "
            f"if kwargs.get('inspection_{name}') is None else kwargs['inspection_{name}']"
        )
    return out


def _gen_host_wrapper_pass(intermediates: List[Dict], indent: str) -> List[str]:
    """Pass allocated inspection buffers into the JIT entry call."""
    return [f"{indent}inspection_{e['name']}=inspection_{e['name']}," for e in intermediates]


def _gen_region_lines(
    region_name: str,
    intermediates: List[Dict],
    by_pp: Dict[str, List[Dict]],
    indent: str,
) -> List[str]:
    """Generate the lines injected before a single closing marker, keyed by region kind."""
    if region_name in PROBE_REGIONS:
        lines: List[str] = []
        for entry in by_pp.get(region_name, []):
            lines.extend(_gen_impl_probe_block(entry, indent))
        return lines
    if region_name == "SIG_IMPL":
        return _gen_sig_impl_kwargs(intermediates, indent)
    if region_name == "SIG_JIT":
        return _gen_sig_jit_kwargs(intermediates, indent)
    if region_name == "CALL_IMPL":
        return _gen_call_impl_kwargs(intermediates, indent)
    if region_name == "HOST_WRAPPER_INSPECT_ALLOC":
        return _gen_host_wrapper_alloc(intermediates, indent)
    if region_name == "HOST_WRAPPER_INSPECT_PASS":
        return _gen_host_wrapper_pass(intermediates, indent)
    return []


def _splice_impl(source: str, intermediates: List[Dict]) -> str:
    """
    Inject generated code before each closing marker. Regions supported:

      - before_nt_loop / inside_nt_loop / after_nt_loop
          → insert pypto.assemble probe blocks for matching intermediates.
      - SIG_IMPL
          → insert inspection_<name>=None kwargs into the _kernel_impl signature.
      - SIG_JIT
          → insert pypto.Tensor-typed inspection kwargs into the JIT entry signature.
      - CALL_IMPL
          → insert keyword-argument pass-through from JIT entry into _kernel_impl.
      - HOST_WRAPPER_INSPECT_ALLOC
          → allocate zero buffers inside host_wrapper(), honoring any kwargs overrides.
      - HOST_WRAPPER_INSPECT_PASS
          → pass the allocated buffers into the JIT-entry call inside host_wrapper().

    Probe blocks (before/inside/after_nt_loop) are grouped by probe_point and
    inserted at the SAME indent as the closing marker (the author is responsible
    for placing the marker pair at the correct block level).
    """
    by_pp: Dict[str, List[Dict]] = {}
    for entry in intermediates:
        by_pp.setdefault(entry["probe_point"], []).append(entry)

    out: List[str] = []
    inside_region: Optional[str] = None
    region_indent = ""
    for line in source.splitlines():
        m_open = MARKER_OPEN.match(line)
        m_close = MARKER_CLOSE.match(line)
        if m_open:
            inside_region = m_open.group(2)
            region_indent = m_open.group(1)
            out.append(line)
            continue
        if m_close and inside_region == m_close.group(2):
            out.extend(_gen_region_lines(inside_region, intermediates, by_pp, region_indent))
            inside_region = None
            out.append(line)
            continue
        out.append(line)
    return "\n".join(out) + ("\n" if source.endswith("\n") else "")


REQUIRED_MARKERS = [
    "SIG_IMPL",                         # _<op>_kernel_impl signature
    "SIG_JIT",                          # <op>_kernel_npu_impl signature
    "CALL_IMPL",                        # inside the JIT entry: call to _<op>_kernel_impl
    "HOST_WRAPPER_INSPECT_ALLOC",     # inside host_wrapper(): buffer allocation
    "HOST_WRAPPER_INSPECT_PASS",      # inside host_wrapper(): JIT call kwargs
]


def _check_required_markers(source: str, filename: str) -> None:
    """Raise ValueError if any of the required wiring markers are missing."""
    missing: List[str] = []
    for marker in REQUIRED_MARKERS:
        if (f"# <<< SNAPSHOT:{marker}" not in source
                or f"# >>> SNAPSHOT:{marker}" not in source):
            missing.append(marker)
    if missing:
        raise ValueError(
            f"missing required marker pair(s) in {filename}: {missing}. "
            "See intermediate-snapshot-automation.md for the marker contract — "
            "the kernel author must place these marker pairs at the signature, "
            "call-site, and host_wrapper locations."
        )


# -----------------------------------------------------------------------------
# Golden-side augmentation
# -----------------------------------------------------------------------------

def _gen_golden_inspect(module_id: str, intermediates: List[Dict]) -> str:
    """
    Produce the module_<k>_inspect() function body. For each intermediate, the
    golden_expression (if given in the manifest) is evaluated per chunk; the
    result is stacked along axis=2 into a [B, H, NT, *shape] tensor.

    If golden_expression is absent for an intermediate, a TODO stub is emitted
    and @pypto-op-debugger must fill it in manually.
    """
    m_num = int(module_id[1:])   # "M2" -> 2
    lines: List[str] = [
        f"def module_{m_num}_inspect(**inputs):",
        f'    """AUTO-GENERATED by snapshot_generator.py. Returns per-iteration intermediates for module {module_id}.',
        "    Output keys match the inspection_<name> buffer names on the impl side.",
        '    """',
        "    import torch",
        "    # Reuse module_<k>'s internals by running the full module, capturing intermediates via closures.",
        "    # This is a stub — @pypto-op-debugger fills in the per-iteration capture logic by looking at",
        "    # modules/<op>_module<suffix_k>_golden.py. The generator cannot AST-rewrite the golden safely.",
        "",
        "    result = {}",
    ]
    for entry in intermediates:
        name = entry["name"]
        expr = entry.get("golden_expression")
        if expr:
            lines.append(f"    # {name}: user-provided expression")
            lines.append(f"    result['{name}'] = {expr}")
        else:
            lines.append(f"    # TODO[@pypto-op-debugger]: fill in the per-iteration computation for {name}.")
            lines.append(f"    #   Expected shape: [B, H, NT, {', '.join(str(s) for s in entry['shape'])}]")
            lines.append(f"    #   dtype:          {entry['dtype']}")
            lines.append(f"    result['{name}'] = None")
    lines.append("    return result")
    lines.append("")
    return "\n".join(lines)


# -----------------------------------------------------------------------------
# Bisect shell script
# -----------------------------------------------------------------------------

class BisectTarget(NamedTuple):
    """The (op, module, case) triple identifying what a bisect script targets."""
    op: str
    module: str
    case: str


def _gen_bisect_sh(target: BisectTarget, modes: List[str], manifest_path: str, device: str = "9") -> str:
    modes_csv = ",".join(modes)
    return f"""#!/usr/bin/env bash
# AUTO-GENERATED by snapshot_generator.py.
# Runs snapshot_bisect.py for {target.op} {target.module} on case {target.case} across modes: {modes_csv}.

set -euo pipefail
cd "$(dirname "$0")/../../.."    # -> repo root from custom/<op>/_debug/

MANIFEST="{manifest_path}"
DEVICE="${{TILE_FWK_DEVICE_ID:-{device}}}"

python skills/pypto-op-verify/scripts/snapshot_bisect.py \\
    --manifest "$MANIFEST" \\
    --modes {modes_csv} \\
    --device "$DEVICE"
"""


# -----------------------------------------------------------------------------
# Top-level driver
# -----------------------------------------------------------------------------

def _locate_sources(manifest_path: str | Path, op: str):
    """
    Resolve repo root, the _debug output dir, and the source impl/golden files.

    The impl source is the widest-suffix existing custom/<op>/<op>_module*.py
    (by Stage 5 the latest staged file is canonical). Raises FileNotFoundError
    if no module file exists or the modular golden is missing.
    """
    repo_root = Path(manifest_path).resolve().parents[3]   # custom/<op>/_debug/manifest.yaml -> repo root
    # parents run outward from the manifest: the _debug dir, then the op dir, then custom, then the repo root
    op_dir = repo_root / "custom" / op
    debug_dir = op_dir / "_debug"
    debug_dir.mkdir(parents=True, exist_ok=True)

    candidates = sorted(op_dir.glob(f"{op}_module*.py"))
    if not candidates:
        raise FileNotFoundError(f"no {op}_module*.py found under {op_dir}")
    source_impl = candidates[-1]

    source_golden = op_dir / "eval" / f"{op}_golden_modular.py"
    if not source_golden.exists():
        raise FileNotFoundError(f"expected golden at {source_golden}")
    return repo_root, debug_dir, source_impl, source_golden


def _verify_markers(impl_src: str, source_name: str, intermediates: List[Dict]) -> None:
    """Check probe-point marker pairs for the needed probe points, plus the required wiring markers."""
    needed_pps = {e["probe_point"] for e in intermediates}
    for pp in needed_pps:
        if f"# <<< SNAPSHOT:{pp}" not in impl_src or f"# >>> SNAPSHOT:{pp}" not in impl_src:
            raise ValueError(
                f"marker pair # <<< SNAPSHOT:{pp} / # >>> SNAPSHOT:{pp} not found in {source_name}. "
                "Add the marker pair around the probe-point region before generating snapshots. "
                "See intermediate-snapshot-automation.md for the marker contract."
            )
    _check_required_markers(impl_src, source_name)


def _build_snapshot_impl(impl_src: str, intermediates: List[Dict], op: str, module: str) -> str:
    """Splice all markers in one pass, then retag the JIT entry so it doesn't collide with the live kernel."""
    impl_with_probes = _splice_impl(impl_src, intermediates)
    return impl_with_probes.replace(
        f"{op}_kernel_npu_impl", f"{op}_{module}_snapshot_kernel_npu_impl"
    ).replace(
        f"{op}_kernel_npu", f"{op}_{module}_snapshot_kernel_npu"
    )


def _build_snapshot_golden(golden_src: str, module: str, intermediates: List[Dict]) -> str:
    """Append the module_<k>_inspect scaffold, or a collision note if it already exists."""
    m_num = int(module[1:])
    inspect_fn = _gen_golden_inspect(module, intermediates)
    if f"def module_{m_num}_inspect" in golden_src:
        # Preserve existing inspect fn; the generator will not clobber hand-
        # written golden capture logic. We append a comment warning that the
        # generator detected a collision.
        return (
            golden_src
            + f"\n\n# NOTE[snapshot_generator]: module_{m_num}_inspect already exists; "
              "generator skipped its scaffold. If the manifest adds NEW intermediates, "
              "extend the existing function by hand.\n"
        )
    return golden_src + "\n\n" + inspect_fn


def _write_artifacts(debug_dir: Path, op: str, module: str, contents: Dict[str, str],
                     dry_run: bool) -> Dict[str, Path]:
    """Compute artifact paths and (unless dry_run) write them, marking the shell script executable."""
    out_impl = debug_dir / f"{op}_{module}_snapshot.py"
    out_golden = debug_dir / f"{op}_golden_modular_snapshot.py"
    out_sh = debug_dir / "run_snapshot_bisect.sh"

    if dry_run:
        logging.info("DRY RUN — would write:")
        for p in (out_impl, out_golden, out_sh):
            logging.info("  %s", p)
        return {"impl": out_impl, "golden": out_golden, "sh": out_sh}

    out_impl.write_text(contents["impl"])
    out_golden.write_text(contents["golden"])
    out_sh.write_text(contents["sh"])
    os.chmod(out_sh, os.stat(out_sh).st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return {"impl": out_impl, "golden": out_golden, "sh": out_sh}


def generate(manifest_path: str | Path, *, dry_run: bool = False) -> Dict[str, Path]:
    """
    Generate the three snapshot artifacts. Returns a dict of
    {artifact_name: output_path}. Raises FileNotFoundError if the source
    module file is missing; raises ValueError if markers are absent.
    """
    m = load_manifest(manifest_path)
    op, module, case = m["op"], m["module"], m["case"]

    repo_root, debug_dir, source_impl, source_golden = _locate_sources(manifest_path, op)
    impl_src = source_impl.read_text()
    golden_src = source_golden.read_text()

    # Check markers for the probe points we need AND the required wiring markers.
    _verify_markers(impl_src, source_impl.name, m["intermediates"])

    # 1. Splice all markers in one pass, then retag the JIT entry name.
    impl_with_probes = _build_snapshot_impl(impl_src, m["intermediates"], op, module)

    # 2. Augment golden — append inspect function at end of golden file.
    augmented_golden = _build_snapshot_golden(golden_src, module, m["intermediates"])

    # 3. Bisect shell script.
    manifest_rel = Path(manifest_path).relative_to(repo_root) \
        if Path(manifest_path).is_absolute() else Path(manifest_path)
    bisect_sh = _gen_bisect_sh(BisectTarget(op, module, case), m["modes"], str(manifest_rel))

    return _write_artifacts(
        debug_dir, op, module,
        {"impl": impl_with_probes, "golden": augmented_golden, "sh": bisect_sh},
        dry_run,
    )


# -----------------------------------------------------------------------------
# CLI
# -----------------------------------------------------------------------------

def _main() -> int:
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    ap = argparse.ArgumentParser(description="Generate snapshot bisection artifacts from a manifest.")
    ap.add_argument("manifest", help="path to custom/<op>/_debug/snapshot_manifest.yaml")
    ap.add_argument("--dry-run", action="store_true", help="do not write files; just print what would be generated")
    args = ap.parse_args()
    paths = generate(args.manifest, dry_run=args.dry_run)
    logging.info("[OK] generated:")
    for k, p in paths.items():
        logging.info("  %-7s -> %s", k, p)
    if not args.dry_run:
        logging.info("\nNext step:")
        logging.info("  bash %s", paths["sh"])
    return 0


if __name__ == "__main__":
    raise SystemExit(_main())
